{
 "title": "Cluster Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "bdb_up{cluster=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (bdb_conns{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Shard Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(redis_connected_clients{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Node Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_up{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "alertlist",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "count(ALERTS{cluster=\"$cluster\", alertstate=\"firing\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(node_available_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Available"
    },
    {
     "expr": "sum(node_provisional_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Provisional"
    },
    {
     "expr": "sum(node_provisional_memory_no_overbooking{cluster=\"$cluster\"})",
     "legendFormat": "Total Provisional (No Overbooking)"
    }
   ]
  },
  {
   "title": "Databases by Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, bdb_avg_latency{} * on(bdb) group_left(bdb_name) bdb_up{} )",
     "legendFormat": "Latency for database: {{bdb_name}} "
    }
   ]
  },
  {
   "title": "Top 10 Requests per Listener",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_total_req{} * on(bdb) group_left(bdb_name) bdb_up{})",
     "legendFormat": "listener {{proxy}} for {{bdb_name}}"
    },
    {
     "expr": "topk(10, sum by(bdb) (bdb_total_req)) > 0",
     "legendFormat": "database: {{bdb}}"
    },
    {}
   ]
  },
  {
   "title": "Top 10 Requests by Database",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bdb_total_req{}) by (bdb) > 0) * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  }
 ]
}