{
 "title": "Cluster Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "bdb_up{cluster=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (bdb_conns{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Shard Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_connected_clients{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_up{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=\"$cluster\", alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(node_available_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Available"
    },
    {
     "expr": "sum(node_provisional_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Provisional"
    },
    {
     "expr": "sum(node_provisional_memory_no_overbooking{cluster=\"$cluster\"})",
     "legendFormat": "Total Provisional (No Overbooking)"
    }
   ]
  },
  {
   "title": "Grow over 1min (Over 100MiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(delta(bdb_used_memory{cluster=\"$cluster\"}[1m])) by (bdb) > 100 * 1024*1024",
     "legendFormat": "BDB #{{bdb}}"
    }
   ]
  },
  {
   "title": "Memory by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used Memory on Node $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "repeat": "node",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{cluster=\"$cluster\", node=\"$node\"} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "database: {{bdb_name}} shard: {{redis}}"
    }
   ]
  },
  {
   "title": "CPU by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage for Node $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_cpu_idle{cluster=\"$cluster\", node=\"$node\"}*100"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Requests per Listener",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_total_req{} * on(bdb) group_left(bdb_name) bdb_up{})",
     "legendFormat": "listener {{proxy}} for {{bdb_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Requests by Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bdb_total_req{} * on(bdb) group_left(bdb_name) bdb_up{}) by (bdb) > 0)",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Used Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, bdb_conns{} * on(bdb) group_left(bdb_name) bdb_up{})",
     "legendFormat": "Connections : {{bdb_name}} "
    },
    {
     "expr": "topk(10, listener_conns{} * on(bdb) group_left(bdb_name) bdb_up{})",
     "legendFormat": "listener #{{proxy}}"
    }
   ]
  },
  {
   "title": "Databases by Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, bdb_avg_latency{} * on(bdb) group_left(bdb_name) bdb_up{} )",
     "legendFormat": "Latency for BDB: {{bdb}} "
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "List of Databases",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "bdb_used_memory{} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Used Memory over 30MB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{} * on(bdb) group_left(bdb_name) bdb_up{} > 30 * 1024 * 1024",
     "legendFormat": "Database: {{bdb_name}} "
    }
   ]
  }
 ]
}