{
 "title": "Database Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "$bdb: Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Status",
     "type": "text",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": {
      "content": "<br>\n<center>\n<b style=\"font-size: 20pt\">$newStatus<b>\n</center>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Key Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Listener Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(listener_total_req{bdb=\"$bdb\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Shard Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(redis_used_memory{cluster=\"$cluster\", bdb=\"$bdb\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$bdb: Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_latency"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_write_latency"
    },
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_read_latency"
    },
    {
     "expr": "bdb_avg_other_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_other_latency"
    },
    {
     "expr": "max_over_time(bdb_avg_latency_max{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "bdb_avg_latency (max over $aggregation)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "main threads (masters)"
    },
    {
     "expr": "bdb_shard_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all threads (masters)"
    },
    {
     "expr": "bdb_fork_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_fork_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all forks (masters)"
    },
    {
     "expr": "bdb_main_thread_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "main threads max (masters)"
    },
    {
     "expr": "bdb_shard_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all threads max (masters)"
    },
    {
     "expr": "sum((delta(redis_process_main_thread_cpu_system_seconds_total{bdb=\"$bdb\",role=\"slave\", cluster=\"$cluster\"}[60s]) + delta(redis_process_main_thread_cpu_user_seconds_total{bdb=\"$bdb\",role=\"slave\", cluster=\"$cluster\"}[60s]))/60)",
     "legendFormat": "Replica main threads"
    },
    {
     "expr": "sum((delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb\",role=\"slave\",cluster=\"$cluster\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb\",role=\"slave\",cluster=\"$cluster\"}[60s]))/60)",
     "legendFormat": "Replica all threads"
    }
   ]
  },
  {
   "title": "Read/Write Misses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_read_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Read Misses"
    },
    {
     "expr": "bdb_write_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Write Misses"
    },
    {
     "expr": "bdb_read_hits{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Read Hits"
    },
    {
     "expr": "bdb_write_hits{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Write Hits"
    }
   ]
  },
  {
   "title": "Keys per Shard",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\", role=\"master\"} or redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\", role=\"master\"}",
     "legendFormat": "redis:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Shard",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb\",cluster=\"$cluster\", role=\"master\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb\",cluster=\"$cluster\", role=\"master\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb\", cluster=\"$cluster\", role=\"master\"}",
     "legendFormat": "shard: {{redis}} role: {{role}} node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "Size of Shards",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{bdb=\"$bdb\",cluster=\"$cluster\", role=\"master\"}",
     "legendFormat": "shard:{{redis}}, role:{{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "$bdb: Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "listener_conns{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "endpoint {{proxy}} node: {{node}}"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "bdb_total_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "total requests"
      },
      {
       "expr": "bdb_other_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "other requests"
      },
      {
       "expr": "bdb_read_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "read requests"
      },
      {
       "expr": "bdb_write_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "write requests"
      },
      {
       "expr": "max_over_time(bdb_total_req_max{cluster=\"$cluster\",bdb=\"$bdb\"}[$aggregation])\n",
       "legendFormat": "total requests (max over $aggregation)"
      }
     ]
    },
    {
     "title": "Ingress/Egress",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "Ingress" }
     ],
     "targets": [
      {
       "expr": "bdb_egress_bytes{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Egress"
      },
      {
       "expr": "bdb_ingress_bytes{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Ingress"
      }
     ]
    },
    {
     "title": "Average Listener Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "listener_acc_latency{bdb=~\"$bdb.*\", cluster=\"$cluster\"} / listener_total_started_res{bdb=~\"$bdb.*\", cluster=\"$cluster\"}",
       "legendFormat": "listener {{proxy}}  node {{node}}"
      }
     ]
    },
    {
     "title": "Synchronization Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "bdb_replicaof_syncer_local_ingress_lag_time{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "database $bdb  src_id {{src_id}}"
      },
      {
       "expr": "bdb_crdt_syncer_local_ingress_lag_time{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "database $bdb crdt src_id {{src_id}}"
      }
     ]
    },
    {
     "title": "Hit Ratio (hits / requests)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(bdb_read_hits{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_write_hits{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_read_req{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_write_req{bdb=\"$bdb\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "$bdb: Hit Ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "$bdb: Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Keys",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "num of keys"
      },
      {
       "expr": "sum(redis_db0_expires{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "num of volatile keys"
      },
      {
       "expr": "sum(max(redis_bigdb0_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "ram keys"
      },
      {
       "expr": "sum(max(redis_bigdb0_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "disk keys"
      },
      {
       "expr": "(sum(max(redis_bigdb0_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) + sum(max(redis_bigdb0_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))) - sum(redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "overlapping keys"
      },
      {
       "expr": "sum(max(redis_bigdb0_dirty{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_dirty{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "dirty keys"
      },
      {
       "expr": "sum(max(redis_bigdb0_clean{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_clean{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "clean keys"
      }
     ]
    },
    {
     "title": "Evicted/Expired Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_evicted_objects{bdb=\"$bdb\", cluster=\"$cluster\"} * on(bdb) group_left(bdb_name) bdb_up{}",
       "legendFormat": "evicted: {{bdb_name}}"
      },
      {
       "expr": "bdb_expired_objects{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "expired: {{bdb_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "used_memory"
      },
      {
       "expr": "bdb_memory_limit{bdb=\"$bdb\", cluster=\"$cluster\"} < bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"} * 1.5",
       "legendFormat": "limit (when low, near used)"
      }
     ]
    }
   ]
  },
  {
   "title": "$bdb: Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard AOF Rewrites / $aggregation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_rewrites{cluster=\"$cluster\", bdb=\"$bdb\"}[$aggregation]) !=0",
     "legendFormat": "Redis {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "Forked Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{cluster=\"$cluster\", bdb=\"$bdb\"} !=0",
     "legendFormat": "BGSAVE {{redis}} node {{node}}"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{cluster=\"$cluster\", bdb=\"$bdb\"} !=0",
     "legendFormat": "AOFRW {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "Total Fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}) / count(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "redis_mem_fragmentation_ratio"
    },
    {
     "expr": "sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"}) / sum(redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "Shard allocator fragmentation"
    },
    {
     "expr": "sum(redis_allocator_resident{bdb=\"$bdb\",cluster=\"$cluster\"}) / sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "shard allocator rss"
    }
   ]
  },
  {
   "title": "Shard RSS Fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_fragmentation{bdb=\"$bdb\", cluster=\"$cluster\"} or redis_mem_fragmentation_ratio{bdb=\"$bdb\", cluster=\"$cluster\"} ",
     "legendFormat": "shard {{redis}} ({{role}})"
    }
   ]
  },
  {
   "title": "BDB sum redis active defrag running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "redis_active_defrag_running{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Delayed fsync - (events / $aggregation)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_delayed_fsync{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "shard {{redis}} ({{role}})"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (#)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"} - redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"} / redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "$bdb: ROF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "BDB (ROF) used RAM for $bdb",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_ram{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "bdb_used_ram"
      },
      {
       "expr": "bdb_ram_limit{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "limit (when low, near used)"
      }
     ]
    },
    {
     "title": "DB ram hit ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "DB ram hit ratio"
      },
      {
       "expr": "bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "read hit ratio"
      },
      {
       "expr": "bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "write hit ratio"
      },
      {
       "expr": "bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "del hit ratio"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "Flash Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "User RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "User Flash Ops for Redis"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\"}[1m])/60",
       "legendFormat": "RAM Ops for Redis {{redis}}"
      },
      {
       "expr": "delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\"}[1m]) / -60",
       "legendFormat": "Flash Ops for Redis {{redis}}"
      }
     ]
    },
    {
     "title": "Flash IO Banwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_read_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_write_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Flash IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_reads{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_writes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      },
      {
       "expr": "bdb_bigstore_io_dels{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "BDB sum redis wait busy key / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_wait_busy_key{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking reads / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_blocking_reads{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB used flash",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "used"
      },
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"} * bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "frag ratio"
      }
     ]
    },
    {
     "title": "BDB postponed clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_postponed_clients{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB blocked clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_blocked_clients{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Number of blocked clients"
      }
     ]
    },
    {
     "title": "BDB ram overhead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"}  / bdb_ram_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "Total Ratio"
      },
      {
       "expr": "redis_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"} / redis_max_ram{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "redis: {{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_blocking_writes{bdb=\"$bdb\",cluster=\"$cluster\"}[1m]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg read io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_read_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg write io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_write_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB objects(values) in FLASH",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_flash{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in flash (sum of all master shards)"
      },
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in ram (sum of all master shards)"
      }
     ]
    },
    {
     "title": "BDB % values in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"} / bdb_no_of_keys{bdb=\"$bdb\",cluster=\"$cluster\"} ",
       "legendFormat": "BDB % values in RAM (masters)"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average master shard % values in RAM"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average slave shard % values in RAM"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest master shard % values in RAM - redsi:{{redis}}"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest slave shard % values in RAM - redsi:{{redis}}"
      }
     ]
    },
    {
     "title": "Shard objects(values) in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per slave shard"
      },
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per master shard"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} ) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}}"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "BDB dirty RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_dirty_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB clean RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_clean_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "RocksDB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_rocks_comp_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "compactions"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "flushes"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_slowdown{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "slowdowns / $aggregation"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_stop{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "stalls / $aggregation"
      }
     ]
    }
   ]
  }
 ]
}